### ISSUE TITLE
Create Citizen python class to generate fake data for simulation

### ISSUE THREAD

**Issue by amy-lei** [dhmit/democracy_africa#1]
Possible features to include: 
- [ ] Name
- [ ] Gender
- [ ] Religious affiliation
- [ ] Job class 
- [ ] Housing 
- [ ] Rural vs Urban 
- [ ] Access to sanitation, water, electricity

**Comment by ryaanahmed** [comment]
Loosk great! @amy-lei @wilke0818 @montsegarza -- on the basis of your discussion yesterday, could you add a tracking issue that covers the full scope of this project (frontend components to be developed, the other bits of the backend, etc.)? see, e.g., #3

**Comment by wilke0818** [comment]
Created #7
