### ISSUE TITLE
Campaign Game Better Story

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/democracy_africa#113]
We want the text in the game play to be engaging and more story-like rather than just instructions.
One way for improve the story is to have text showing the progress from one poll to another.
Also, add more to the intro view.

**Comment by JasonLin43212** [comment]
Branch: `campaign-game-story`

**Comment by JasonLin43212** [comment]
I was playing around and then this happened. I think it has something to do with the random number generator?
![Screenshot from 2020-06-24 14-12-57](https://user-images.githubusercontent.com/27793365/85610256-d5301f00-b624-11ea-97c3-49f33499c413.png)

**Comment by mscuthbert** [comment]
off by 1 error?
