### ISSUE TITLE
Campaign Game Responsive 2.0

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/democracy_africa#128]
When we do responsive design, we want to think about the way that the user interprets the information on the screen.

- [x] Make submit buttons and tables 100% width and remove maps on phone sized windows
We can use `d-none d-md`  to make a div vanish below medium size
- [x] In the feedback view, move the map to the top so that the user can interact with that first.
- [x] Left align the text in feedback because users tend to look at the left side to scan the text (Justice)
- [x] Have a fixed number of citizens per row so that it there is less noise. (Justice)
- [x] Get rid of popovers on smaller sizes (Justice) 
- [x] Fix any other design issues that seem to appear on smaller screens
- [x] Shrink the map
- [x] Intro page, move instructions to the top (Justice)

**Comment by JasonLin43212** [comment]
Branch: `style`

**Comment by JusticeV452** [comment]
![image](https://user-images.githubusercontent.com/55002917/85621306-13343f80-b633-11ea-9c33-d633d324c49a.png)
