### ISSUE TITLE
Backend for heat map for democracy scores

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/democracy_africa#4]
- [x] Make component for project
- [x] Set up an endpoint `/api/democracy_scores`
- [x] Send _something_ to the front end to make sure it works
- [x] Parse the data set and then send to front end (figure out how to best format the csv)

**Comment by JasonLin43212** [comment]
- [x] update backend with country codes once #2 is merged

**Comment by ryaanahmed** [comment]
@JasonLin43212  --  #2 is merged, so go ahead.

Rather than waiting to complete the whole subproject, please make a PR now that this work is done, so I can review. Thanks!
