### ISSUE TITLE
Add missing countries to our v-dem 1981-2018 dataset

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/democracy_africa#5]
A few countries are missing from our dataset extracted from v-dem (see discussion below). Let’s complete it:

- [x] Download the full v-dem dataset from https://www.v-dem.net/en/data/data-version-9/ (you'll want the `Country-Year: V-Dem Core` version, in CSV format)
- [x] Isolate the rows for the missing countries from 1981-2018
- [x] Isolate the variables that we're interested in from the existing dataset
- [x] Add what remains to the existing dataset

**Comment by JasonLin43212** [comment]
Seems like Algeria is not the only country missing. The following countries are also missing: Egypt, Morocco, Tunisia, Libya, and Djibouti

**Comment by ryaanahmed** [comment]
Thanks, @JasonLin43212 — the reason for this just hit me: Evan’s course was focused on _subsaharan_ Africa. Let’s continue to compile a complete dataset, and check in with him about this issue.

**Comment by mscuthbert** [comment]
Ah yes -- those countries are generally thought to be culturally more connected to the Middle East and Europe.

**Comment by ryaanahmed** [comment]
@evanlieb -- checking in with you here about what you'd like us to do. Although the focus of the course was Sub-Saharan Africa, should we go ahead and compile a complete dataset for this project? (see above discussion)

**Comment by evanlieb** [comment]
hi -- that's correct, those countries were out because in most datasets, they would be linked to the "region" known as "Middle East and North Africa," and I think that when I pulled down the data for you all, i just included "Africa==1". That said, I certainly have no objection to including them, and some projects, such as Afrobarometer.org also include some African countries. IN SHORT, if it is easy enough at this stage to include those countries, you may as well do do, they will be in the V-DEM dataset

**Comment by ryaanahmed** [comment]
@evanlieb -- great -- straightforward to add them. Is the period 1981-2018 (from your existing dataset) what you'd like represented?

**Comment by evanlieb** [comment]
Yes sounds good!

Sent from my iPhone

On Jan 24, 2020, at 11:55 AM, Ryaan Ahmed <notifications@github.com> wrote:

﻿

@evanlieb<https://github.com/evanlieb> -- great -- straightforward to add them. Is the period 1981-2018 (from your existing dataset) what you'd like represented?

**Comment by JasonLin43212** [comment]
Another note: some countries may be in the CSV file but they do not have all the years. For example, Eritrea only goes from 1993 - 2018, so the missing years need to be added in

**Comment by evanlieb** [comment]
Eritrea only became independent from Ethiopia in 1993 I believe.. so you can “gray it out” or just include as part of Ethiopia before that.

Sent from my iPhone

On Jan 27, 2020, at 9:07 PM, Jason Lin <notifications@github.com> wrote:

﻿

Another note: some countries may be in the CSV file but they do not have all the years. For example, Eritrea only goes from 1993 - 2018, so the missing years need to be added in

**Comment by JasonLin43212** [comment]
With the way that our visualization works, it will be grayed out.

**Comment by wilke0818** [comment]
@evanlieb I am writing a script to grab the missing countries and their data from the Country-Year: V-Dem Core dataset, but when I look for certain features that you have in your compiled dataset, I can't find those in the v-dem data.

These are the features/headers that I can't find:
v2elboycot, v2lpname, v2slpname, v2tlpname, v2svstterr, v2peprisch, v2pesecsch , v2smonex,
e_migdppc, e_mipopula, gdpcapl, ethfrac, relfrac, numlang, colbrit, colfra, gdpcap_currusd,
elecaccessrur

**Comment by evanlieb** [comment]
i am going to swing by around 4pm today so can help out with any issues then. a few of the variables below came from another dataset, but most of the information there is captured in other v-dem variables. in short… i wouldn’t worry about those

***

Evan S Lieberman
Total Professor of Political Science and Contemporary Africa
Massachusetts Institute of Technology (MIT)

email: evanlieb@mit.edu <mailto:evanlieb@mit.edu>
website: evanlieberman.org <http://evanlieberman.org/>

**Comment by wilke0818** [comment]
See #23

**Comment by ryaanahmed** [comment]
Closed via #23
